#! /bin/bash

user=$1
lineToStart=$2

ps -u $user | tail -n +$lineToStart > ${user}.pss

while read -r line; do
	#printf '%s\n' "$line"
	spaceIndex=`expr index "$line" ' '`
	pid=${line:0:$[spaceIndex-1]}
	echo 'killing' $pid
	kill -kill $pid
done < ${user}.pss

rm ${user}.pss
