#! /bin/bash

if [ $# -eq 0 ];then
	echo 'call with name of executable file'
	exit
fi

# Thanks to Fall 2016 student Zach Grow for suggesting use
# of the --track-origins=yes flag in this bash script.

do_cmd "valgrind --track-origins=yes --tool=memcheck --leak-check=full $1"
