#! /bin/bash

# archive linux setup files in home directory,
# copying files into git repository directory and
# creating compressed tar file named by $dir_name

dir_name=linux_setup
files='.bash_profile .gdbinit .vimrc'

cd
mkdir $dir_name
cp $files linux_setup
tarz $dir_name
rm -rf $dir_name
