#! /bin/bash

# archive *.c, *.h, makefile recursively in directory $1,
# creating compressed tar file name $2.tar.gz

find $1 -type f -print | egrep '(\.[ch]|[Mm]akefile)$' > __files__
tar cvfz $2.tar.gz -T __files__
chmod 600 $2.tar.gz
rm __files__
