#! /bin/bash

# archive linux setup files in home directory,
# creating compressed tar file named by $fname

fname=linux_setup.tar.gz

rm -f $fname.tar.gz
tar --create --preserve-permissions --gzip --file $fname \
	.bash_profile .hgrc .gdbinit .vimrc
