#! /bin/bash

# archive all files recursively in directory $1,
# creating compressed tar file named $1.tar.gz

if [ $# -eq 0 ];then
	echo 'call with directory name -> <dirname>.tar.gz'
	exit
fi

rm -f $1.tar.gz			# remove previous file, if any

tar --create --preserve-permissions --gzip --file $1.tar.gz $1

chmod 600 $1.tar.gz
